In [1]:
import numpy as np
import pandas as pd

In [2]:
rng = np.random.RandomState(42)


In [192]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

In [3]:
pd.__version__

'0.23.4'

In [193]:
!python --version

Python 3.6.6


In [4]:
# pandas series object
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
print(data.values)
print(data.index)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)


In [6]:
data.index=[2,5,3,7] 
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [7]:
data.index=['a','b','c','d'] 
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data['b']

0.5

In [9]:
# series from dictionary
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)
# By  default,  a  Series will  be  created  where  the  index  is  drawn  from  the  sorted  keys.
print(population)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [10]:
population.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [11]:
population['California']

38332521

In [12]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [13]:
# data can be a scalar, which is repeated to fill the specified index
pd.Series(5,index = [100,200,300])

100    5
200    5
300    5
dtype: int64

In [14]:
# index defaults to the sorted dictionary keys
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [15]:
# The  Series  is  populated  only  with  the  explicitly  identified keys
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [16]:
# Pandas DataFrame Object
area_dict = {'California': 423967,
             'Texas': 695662, 
             'New York': 141297,
             'Florida': 170312, 
             'Illinois': 149995}
area = pd.Series(area_dict)
states = pd.DataFrame({'population':population,
                      'area':area})  # population is a series like area
print(states,'\n')
print(states.index,'\n')
print(states.values,'\n')
print(states.columns,'\n')

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995 

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object') 

[[38332521   423967]
 [26448193   695662]
 [19651127   141297]
 [19552860   170312]
 [12882135   149995]] 

Index(['population', 'area'], dtype='object') 



In [17]:
#  In  a  two-dimensional  NumPy  array,
# data[0] will return the first row. 
# For a DataFrame, 
# data['col0'] will return the first column

print(states['area'])

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64


In [18]:
# Construction DataFrames Objects
# from single series object
pd.DataFrame(population,columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [19]:
# from a list of dictionaries
data = [{'a':i,'b':2*i} for i in range(3)]
print(data)
pd.DataFrame(data)


[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]


a  b
0  0  0
1  1  2
2  2  4

In [20]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [21]:
# from a dictionary of series objects
pd.DataFrame({'population':population,
             'area':area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [22]:
# from two dimensional numpy array
pd.DataFrame(np.random.rand(3,2),
            columns = ['foo','bar'],
            index=['a','b','c'])

foo       bar
a  0.538501  0.809080
b  0.130148  0.419659
c  0.677027  0.579376

In [23]:
# from a numpy structured array
a = np.zeros(2,dtype=[('A','i8'),('B','f8')])
pd.DataFrame(a)

A    B
0  0  0.0
1  0  0.0

In [24]:
# Pandas Index Object
ind = pd.Index([2, 3, 5, 7, 11])
print(ind[1],'\n')
print(ind[::2],'\n')
print(ind.size,ind.shape,ind.dtype)

3 

Int64Index([2, 5, 11], dtype='int64') 

5 (5,) int64


In [25]:
#indexes are immutable
# ind[1] = 0 # gives error

In [26]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

# intersection
indA & indB # indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [27]:
# Union
indA | indB # indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [28]:
# symmetric difference
indA ^ indB # indA.symmetric_difference(ind_B)

Int64Index([1, 2, 9, 11], dtype='int64')

In [29]:
# Data selection in series
# series as dictionary
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [30]:
'a' in data

True

In [31]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [32]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [33]:
# slicing
print(data['a':'c'],'\n') # 'c' is included
print(data[0:2]) # index at 2 place excluded

a    0.25
b    0.50
c    0.75
dtype: float64 

a    0.25
b    0.50
dtype: float64


In [34]:
# masking
data[(data>0.3)&(data<0.8)]
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [35]:
# fancy indexing
data[['a','d']]

a    0.25
d    1.00
dtype: float64

In [36]:
# indexers loc,iloc
data = pd.Series(['a', 'b', 'c','d'], 
                 index=[1, 3, 5, 7])
print(data.iloc[1:3],'\n') # implicit indexing, python style positional integer index starting with 0
print(data.loc[1:3]) # explicit indexing, includes end value

3    b
5    c
dtype: object 

1    a
3    b
dtype: object


In [37]:
# Data selection in DataFrames
#dictionary style
area = pd.Series({'California': 423967, 
                   'Texas': 695662,
                   'New York': 141297, 
                   'Florida': 170312,
                   'Illinois': 149995})
pop = pd.Series({'California': 38332521, 
                 'Texas': 26448193,
                 'New York': 19651127, 
                 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
print(data,'\n')
print(data['area'])

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135 

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64


In [38]:
data.area # attribute style access

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [39]:
data.area is data['area']

True

In [40]:
data.pop is data['pop'] # attribute type access should be avoided

False

In [41]:
data['density']=data['pop']/data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [42]:
# DataFrame as 2D array
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [43]:
data.T # transpose

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [44]:
# data[0] # invalid
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [45]:
data.iloc[0]

area       4.239670e+05
pop        3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

In [46]:
data.loc['Florida']

area       1.703120e+05
pop        1.955286e+07
density    1.148061e+02
Name: Florida, dtype: float64

In [47]:
data.loc[:,'area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [48]:
# masking and fancy indexing
data.loc[data['density'] > 100,['pop','density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [49]:
data.iloc[0,2] = 90 
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [50]:
# Operations on data
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [51]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                 columns = ['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [52]:
np.exp(ser) 

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [53]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [54]:
# index alignment in series
A = pd.Series([2, 4, 6], 
              index=[0, 1, 2])
B = pd.Series([1, 3, 5], 
              index=[1, 2, 3])

print(A + B,'\n')
print(A.index | B.index) # union

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64 

Int64Index([0, 1, 2, 3], dtype='int64')


In [55]:
A.add(B,fill_value=0) # missing values in series will be treated as 0

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [56]:
# index alignment in DataFrame
a = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
a

A   B
0  1  11
1  5   1

In [57]:
b = pd.DataFrame(rng.randint(0,10,(3,3)),
                 columns= list('BAC'))
b

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [58]:
a + b
# indices are aligned correctly irrespective of their order in the two objects,
# and indices in the result are sorted

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [59]:
print(a,'\n')
print(a.stack(),'\n')
fill = a.stack().mean()
print(fill,'\n')
print(a.add(b,fill_value=fill))

   A   B
0  1  11
1  5   1 

0  A     1
   B    11
1  A     5
   B     1
dtype: int64 

4.5 

      A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5


In [60]:
# subtraction between a two-dimensional array and one of its rows is
# applied row-wise
a = rng.randint(10,size=(3,4))
print(a,'\n')
print(a - a[0])

[[3 8 2 4]
 [2 6 4 8]
 [6 1 3 8]] 

[[ 0  0  0  0]
 [-1 -2  2  4]
 [ 3 -7  1  4]]


In [61]:
df = pd.DataFrame(a,columns=list('QRST'))
print(df,'\n')
print(df - df.iloc[0])

   Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8 

   Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4


In [62]:
# to operate column wise use axis
print(df.subtract(df.iloc[:,0],axis =0))

   Q  R  S  T
0  0  5 -1  1
1  0  4  2  6
2  0 -5 -3  2


In [63]:
halfrow = df.iloc[0,::-1]
print(halfrow)

T    4
S    2
R    8
Q    3
Name: 0, dtype: int64


In [64]:
# preservation  and  alignment  of  indices  and  columns  means  that  operations  on
# data in Pandas will always maintain the data context
df - halfrow

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [65]:
# Handling missing Data
# None: Pythonic missing data
# None is  a  Python  object,  it  cannot  be
# used  in  any  arbitrary  NumPy/Pandas  array,  
# but  only  in  arrays  with  data  type 'object'

In [66]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

# Using sum() or min() across an array with a None value,
# generally gives an error.


dtype = object
58.9 ms ± 3.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
2.78 ms ± 192 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [67]:
# NaN: Missing numerical data
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [68]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)
# NaN  is  specifically  a  floating-point  value;  
# There  is  no  equivalent NaN value for integers, strings, or other types.

(8.0, 1.0, 4.0)

In [69]:
# detecting null values
data = pd.Series([1,np.nan,'hello',None])
print(data,'\n')
print(data.isnull(),'\n')
print(data.notnull(),'\n')
print(data[data.notnull()]) # using boolean mask

0        1
1      NaN
2    hello
3     None
dtype: object 

0    False
1     True
2    False
3     True
dtype: bool 

0     True
1    False
2     True
3    False
dtype: bool 

0        1
2    hello
dtype: object


In [70]:
# dropping null values
data.dropna()

0        1
2    hello
dtype: object

In [71]:
df=pd.DataFrame([[1,np.nan,2],
                 [2,3,5],
                 [np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [72]:
df.dropna(axis = 'index',subset = [0])
# subset : array-like, optional
#     Labels along other axis to consider, e.g. if you are dropping rows
#     these would be a list of columns to include.

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5

In [73]:
df.dropna() # drops all rows in which any null value is preset

0    1  2
1  2.0  3.0  5

In [74]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [75]:
df[3] = np.nan # making whole column as NaN
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [76]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [77]:
df.dropna(axis='rows',thresh=3)
# thresh parameter lets you specify a minimum number
# of non-null values for the row/column to be kept

0    1  2   3
1  2.0  3.0  5 NaN

In [78]:
# filling null values
data = pd.Series([1, np.nan, 2, None, 3], 
                 index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [79]:
data.fillna(0) # fill missing values with 0

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [80]:
data.fillna(method='ffill')
# pad / ffill: propagate last valid observation forward to next valid
# backfill / bfill: use NEXT valid observation to fill gap

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [81]:
print(df,'\n')
print(df.fillna(method='ffill',axis='columns'))

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN 

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0


In [82]:
# Hierarchical Indexing
index = [('California', 2000), ('California', 2010),
    ('New York', 2000), ('New York', 2010),
    ('Texas', 2000), ('Texas', 2010)]


In [83]:
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

In [84]:
# series 
# not the best way
pop=pd.Series(populations,index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [85]:
# slicing 
pop[('California',2010):('Texas',2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [86]:
# complex operations
# selecting all values for 2010
pop[[i for i in pop.index if i[1]== 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [87]:
# Pandas # Better Way
index = pd.MultiIndex.from_tuples(index) # or for multidim array : from_arrays 
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [88]:
pd.MultiIndex.from_product([['a','b'],[1,2]]) # cartesian product

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [89]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [90]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [95]:
# names for multilevel index
pop.index.names = ['state','year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [91]:
# MultiIndex as extra dimension
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [92]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [93]:
# add another column
pop_df=pd.DataFrame({'total':pop,
                    'under18':[9267089, 9284094,
                               4687374, 4318033,
                               5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [94]:
# fraction of people under 18 by year
pop_df['under18']/pop_df['total']

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [98]:
# MultiIndex for columns
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],
                                  names = ['year','visit'])
columns = pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']],
                                    names = ['subject','type'])
print(index,'\n')
print(columns)

MultiIndex(levels=[[2013, 2014], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['year', 'visit']) 

MultiIndex(levels=[['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]],
           names=['subject', 'type'])


In [99]:
#mock data
data = np.round(np.random.randn(4,6),1)
data[:,::2]*=10
data += 37
data

array([[40. , 34.7, 60. , 36.7, 34. , 37. ],
       [44. , 36.9, 50. , 36.6, 33. , 38.1],
       [24. , 36. , 41. , 39.5, 38. , 38. ],
       [30. , 36.2, 40. , 35.9, 45. , 36.9]])

In [101]:
# create a dataframe
health_data = pd.DataFrame(data,index=index,columns=columns)
health_data # 4 dimensional data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  34.7  60.0  36.7  34.0  37.0
     2      44.0  36.9  50.0  36.6  33.0  38.1
2014 1      24.0  36.0  41.0  39.5  38.0  38.0
     2      30.0  36.2  40.0  35.9  45.0  36.9

In [134]:
# health_data.unstack(level = [1,0]).index # topic not clear

In [135]:
# Indexing and slicing
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [143]:
print(pop['California',2000],'\n')
print(pop['California'])  # partial indexing only if MultiIndex is sorted

33871648 

year
2000    33871648
2010    37253956
dtype: int64


In [144]:
pop[:,2000]  # to be used with sorted indices only

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [145]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  34.7  60.0  36.7  34.0  37.0
     2      44.0  36.9  50.0  36.6  33.0  38.1
2014 1      24.0  36.0  41.0  39.5  38.0  38.0
     2      30.0  36.2  40.0  35.9  45.0  36.9

In [165]:
health_data['Guido','HR']

year  visit
2013  1        60.0
      2        50.0
2014  1        41.0
      2        40.0
Name: (Guido, HR), dtype: float64

In [158]:

health_data.loc[:,['Bob','HR']] # returns dataframe

subject      Bob      
type          HR  Temp
year visit            
2013 1      40.0  34.7
     2      44.0  36.9
2014 1      24.0  36.0
     2      30.0  36.2

In [159]:
health_data.loc[:,('Bob','HR')] # returns series

year  visit
2013  1        40.0
      2        44.0
2014  1        24.0
      2        30.0
Name: (Bob, HR), dtype: float64

In [161]:
# health_data.loc[(:, 1), (:, 'HR')] # error while slicing within tuples

SyntaxError: invalid syntax (<ipython-input-161-fb34fa30ac09>, line 1)

In [174]:
# using IndexSlice objects
idx = pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      40.0  60.0  34.0
2014 1      24.0  41.0  38.0

In [181]:
# Rearranging multi index
# Many of the MultiIndex slicing operations will fail if the index is not sorted


In [182]:
index = pd.MultiIndex.from_product([[2,1],
                                    ['a', 'c', 'b']])
data = pd.Series(np.random.rand(6), 
                 index=index)
data.index.names = ['int', 'char']
data

int  char
2    a       0.589431
     c       0.870285
     b       0.927501
1    a       0.363239
     c       0.454339
     b       0.239902
dtype: float64

In [183]:
data.sort_index() 

int  char
1    a       0.363239
     b       0.239902
     c       0.454339
2    a       0.589431
     b       0.927501
     c       0.870285
dtype: float64

In [184]:
# stack, unstack
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [185]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [186]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [187]:
pop.unstack().stack() 

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [188]:
# Index setting and resetting
# rearrange hierarchical data to turn the index labels into columns
pop_flat = pop.reset_index(name = 'population') # name: The name to use for the column containing the original Series values
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [189]:
# multiindexing
pop_flat.set_index(['state','year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [190]:
# Data Aggregations on Multi Indices
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  34.7  60.0  36.7  34.0  37.0
     2      44.0  36.9  50.0  36.6  33.0  38.1
2014 1      24.0  36.0  41.0  39.5  38.0  38.0
     2      30.0  36.2  40.0  35.9  45.0  36.9

In [191]:
data_mean = health_data.mean(level='year')
data_mean

subject   Bob       Guido          Sue       
type       HR  Temp    HR   Temp    HR   Temp
year                                         
2013     42.0  35.8  55.0  36.65  33.5  37.55
2014     27.0  36.1  40.5  37.70  41.5  37.45

In [ ]:
## Advance topic: pd.Panel and pd.Panel4D (3d and 4d generalization of 1d series and 2d dataframe structures)

In [194]:
# Combining Datasets
make_df('ABC',range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [195]:
# concatenation

ser1 = pd.Series(['A', 'B', 'C'], 
                 index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], 
                 index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [197]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1,'\n') 
print(df2,'\n')
print(pd.concat([df1, df2])) # default row wise

    A   B
1  A1  B1
2  A2  B2 

    A   B
3  A3  B3
4  A4  B4 

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [204]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(pd.concat([df3, df4],axis ='columns')) # axis = 1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [206]:
# if indices are same then they are duplicated
print(pd.concat([df1,df1]))

    A   B
1  A1  B1
2  A2  B2
1  A1  B1
2  A2  B2


In [208]:
# catching repeated indices
try:
    pd.concat([df1,df1],verify_integrity=True)
except ValueError as e:
    print('ValueError:',e)

ValueError: Indexes have overlapping values: Int64Index([1, 2], dtype='int64')


In [210]:
# ignoring index
print(pd.concat([df1,df1],ignore_index=True))

    A   B
0  A1  B1
1  A2  B2
2  A1  B1
3  A2  B2


In [223]:
# using multiindexing in concat
print(pd.concat([df1,df1],keys=['first','second']))

           A   B
first  1  A1  B1
       2  A2  B2
second 1  A1  B1
       2  A2  B2


In [227]:
# concat with joins
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5,'\n')
print(df6,'\n')
print(pd.concat([df5, df6],sort=False)) # for deprication warning

    A   B   C
1  A1  B1  C1
2  A2  B2  C2 

    B   C   D
3  B3  C3  D3
4  B4  C4  D4 

     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4
